### ISSUE TITLE
still some trend line funny business in one analysis

### ISSUE THREAD

**Issue by rconstanzo** [madwort/improv-analysis#8]
for some reason the trend line here still goes odd:
http://www.rodrigoconstanzo.com/analyses/?q=ucb

at 1:30 and 1:38 or thereabouts. looking through the csv there isn't anything weird in the data, other than it being higher granularity than other timings:
01:29.994->01:30.560->01:33.286
01:37.895->01:38.654->01:45.740

**Comment by madwort** [comment]
Ok, I think I've figured out what's causing the bug, but I'm still working on a fix. 

In the current method of drawing a trendline, for each datapoint in the analysis, I calculate the value that the regression line has at that point & graph that as a second axis. This causes issues with the charting lib dimple as it rounds points to per second for display & when there are multiple points in the same second, we get a wiggle in the chart. I mostly solved this by removing all but one regression points as we go along, but I did this by rounding down. In some cases, we round down but dimple rounds _up_, so this second point now has no regression datapoint & we see a wiggle _downwards_. 

The fix is to mimic dimple's rounding algorithm - it's not Math.floor() & it's not Math.round(), but what is it?

**Comment by madwort** [comment]
Trial & error on the rounding...

1.895 => 2
1.850 => 2
1.830 => 2
1.826 => 2

1.825 => 1
1.820 => 1
1.800 => 1
1.795 => 1

**Comment by rconstanzo** [comment]
For the time being I can just massage the numbers back to somewhere else. This is the only analysis that's this super granular with times, and only because I was using a different program to get the times from.

**Comment by madwort** [comment]
That would be good for now - I did the rendering for these lines this way because it was going to be quick & easy, but I've reached my threshold for fiddliness with it, so longer-term I'm going to switch it out for a different way... (drawing the line directly with d3, rather than using dimple)

**Comment by rconstanzo** [comment]
Yeah that works.

Numbers adjusted to:
01:29.594->01:30.560->01:33.286
01:37.495->01:38.654->01:45.740
